# Generated by Django 4.1.7 on 2023-04-04 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_total']},
        ),
    ]
